### ISSUE TITLE
List index out of range error in toggle_highlight_cell() func when clicked some cell IN plus table

### ISSUE THREAD

**Issue by eyakm1** [ShashkovS/plus_reader#1]
Error log:
```
INFO     [2017-09-28 12:50:10,924] 171 575 # This is click coordinates 
INFO     [2017-09-28 12:50:10,924] [2, 23] # This is cell coordinates 
Traceback (most recent call last):
  File "C:/Users/s22b_abishev.SCH179/PycharmProjects/plus_reader/plus_reader\plus_highlighting.py", line 107, in mousePressEvent
    image.toggle_highlight_cell(*cell_pos)
  File "C:/Users/s22b_abishev.SCH179/PycharmProjects/plus_reader/plus_reader\plus_highlighting.py", line 33, in toggle_highlight_cell
    self.vertical_coords[j]+bw, self.vertical_coords[j + 1]-bw
IndexError: list index out of range

```

What's going wrong?

**Comment by ShashkovS** [comment]
@eyakm1, fixed in https://github.com/ShashkovS/plus_reader/commit/51417590b86fa3705656c0eeec4a9152d61de536
